require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/bets", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Bet. As you add validations to Bet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Bet.create! valid_attributes
      get bets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      bet = Bet.create! valid_attributes
      get bet_url(bet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_bet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      bet = Bet.create! valid_attributes
      get edit_bet_url(bet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Bet" do
        expect {
          post bets_url, params: { bet: valid_attributes }
        }.to change(Bet, :count).by(1)
      end

      it "redirects to the created bet" do
        post bets_url, params: { bet: valid_attributes }
        expect(response).to redirect_to(bet_url(Bet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Bet" do
        expect {
          post bets_url, params: { bet: invalid_attributes }
        }.to change(Bet, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post bets_url, params: { bet: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bet" do
        bet = Bet.create! valid_attributes
        patch bet_url(bet), params: { bet: new_attributes }
        bet.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the bet" do
        bet = Bet.create! valid_attributes
        patch bet_url(bet), params: { bet: new_attributes }
        bet.reload
        expect(response).to redirect_to(bet_url(bet))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        bet = Bet.create! valid_attributes
        patch bet_url(bet), params: { bet: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested bet" do
      bet = Bet.create! valid_attributes
      expect {
        delete bet_url(bet)
      }.to change(Bet, :count).by(-1)
    end

    it "redirects to the bets list" do
      bet = Bet.create! valid_attributes
      delete bet_url(bet)
      expect(response).to redirect_to(bets_url)
    end
  end
end
